# Generated by Django 3.2 on 2022-08-16 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inflasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandang', models.IntegerField()),
                ('sembako', models.IntegerField()),
                ('perumahan', models.IntegerField()),
                ('kesehatan', models.IntegerField()),
                ('transprotasi', models.IntegerField()),
                ('informasi', models.IntegerField()),
                ('rekreasi', models.IntegerField()),
                ('pendidikan', models.IntegerField()),
                ('penyedia_pangan', models.IntegerField()),
                ('perawatan_pribadi', models.IntegerField()),
                ('total_inflasi', models.IntegerField()),
                ('dibuat', models.DateTimeField(auto_now_add=True, verbose_name=django.utils.timezone.now)),
                ('diubah', models.DateTimeField(auto_now=True, verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProdukDomestikRegionalBruto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanian_kehutanan_perikanan', models.IntegerField(max_length=20)),
                ('pertambangan_penggalian', models.IntegerField(max_length=20)),
                ('industri_pengolahan', models.IntegerField(max_length=20)),
                ('pengadaan_air_pengelolaan_sampah_dan_daur_ulang', models.IntegerField(max_length=20)),
                ('kontruksi', models.IntegerField(max_length=20)),
                ('perdagangan_besar_eceran_reparasi_mobil_motor', models.IntegerField(max_length=20)),
                ('transportasi_pergudangan', models.IntegerField(max_length=20)),
                ('penyediaan_akomodasi_makan_minum', models.IntegerField(max_length=20)),
                ('informasi_komunikasi', models.IntegerField(max_length=20)),
                ('keuangan_asuransi', models.IntegerField(max_length=20)),
                ('real_estat', models.IntegerField(max_length=20)),
                ('jasa_perusahaan', models.IntegerField(max_length=20)),
                ('administrasi', models.IntegerField(max_length=20)),
                ('jasa_pendidikan', models.IntegerField(max_length=20)),
                ('jasa_kesehatan', models.IntegerField(max_length=20)),
                ('jasa_lainnya', models.IntegerField(max_length=20)),
                ('total_pdrb', models.IntegerField(max_length=20)),
                ('dibuat', models.DateField(auto_now_add=True, verbose_name=django.utils.timezone.now)),
                ('diubah', models.DateField(auto_now=True, verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kota', models.TextField(max_length=50)),
                ('inflasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inflasi_kota', to='bps.inflasi')),
                ('pdrb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdrb_kota', to='bps.produkdomestikregionalbruto')),
            ],
        ),
    ]
