# Generated by Django 3.2 on 2022-08-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0002_auto_20220824_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdrb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('PDRB Migas', 'PDRB Migas'), ('Distribusi PDRB Migas', 'Distribusi PDRB Migas'), ('Laju Pertumbuhan PDRB Migas', 'Laju Pertumbuhan PDRB Migas'), ('PDRB Migas', 'PDRB Non Migas'), ('Distribusi PDRB Non Migas', 'Distribusi PDRB Non Migas'), ('Laju Pertumbuhan PDRB Non Migas', 'Laju Pertumbuhan PDRB Non Migas')], max_length=100)),
                ('a', models.FloatField(verbose_name='Pertanian dan Kehutanan')),
                ('b', models.FloatField(verbose_name='Pertambangan dan Penggalian')),
                ('c', models.FloatField(verbose_name='Industri')),
                ('d', models.FloatField(verbose_name='Listrik dan Gas')),
                ('e', models.FloatField(verbose_name='Air, Sampah/Limbah dan Daur Ulang')),
                ('f', models.FloatField(verbose_name='Kontruksi')),
                ('g', models.FloatField(verbose_name='Perdagangan, Reparasi Mobil/Sepeda Motor')),
                ('h', models.FloatField(verbose_name='Transportasi dan Pergudangan')),
                ('i', models.FloatField(verbose_name='Penyediaan Akomodasi dan Makan Minum')),
                ('j', models.FloatField(verbose_name='Informasi dan Komunikasi')),
                ('k', models.FloatField(verbose_name='Jasa Keuangan dan Asuransi')),
                ('l', models.FloatField(verbose_name='Real Estate')),
                ('m_n', models.FloatField(verbose_name='Jasa Perusahaan')),
                ('o', models.FloatField(verbose_name='Administrasi Pemerintahan, Pertahanan, dan Jaminan Sosial Wajib')),
                ('p', models.FloatField(verbose_name='Jasa Pendidikan')),
                ('q', models.FloatField(verbose_name='Jasa Kesehatan dan Kegiatan Sosial')),
                ('r_s_t_u', models.FloatField(verbose_name='Jasa Lainnya')),
                ('total_pdrb', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('tanggal', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produk Domestik Regional Bruto',
                'verbose_name_plural': 'Produk Domestik Regional Bruto Dengan Migas',
            },
        ),
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelamin', models.CharField(choices=[('LK', 'Laki-Laki'), ('PR', 'Perempuan')], max_length=15)),
                ('a', models.IntegerField(verbose_name='0-4 Tahun')),
                ('b', models.IntegerField(verbose_name='5-9 Tahun')),
                ('c', models.IntegerField(verbose_name='10-14 Tahun')),
                ('d', models.IntegerField(verbose_name='15-19 Tahun')),
                ('e', models.IntegerField(verbose_name='20-24 Tahun')),
                ('f', models.IntegerField(verbose_name='25-29 Tahun')),
                ('g', models.IntegerField(verbose_name='30-34 Tahun')),
                ('h', models.IntegerField(verbose_name='35-39 Tahun')),
                ('i', models.IntegerField(verbose_name='40-44 Tahun')),
                ('j', models.IntegerField(verbose_name='45-49 Tahun')),
                ('k', models.IntegerField(verbose_name='50-54 Tahun')),
                ('l', models.IntegerField(verbose_name='55-59 Tahun')),
                ('m', models.IntegerField(verbose_name='60-64 Tahun')),
                ('n', models.IntegerField(verbose_name='65-69 Tahun')),
                ('o', models.IntegerField(verbose_name='70-74 Tahun')),
                ('p', models.IntegerField(verbose_name='75+ Tahun')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendudukKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kec', models.CharField(choices=[('Dayeuhluhur', 'Dayeuhluhur'), ('Wanareja', 'Wanareja'), ('Majenang', 'Majenang'), ('Cimanggu', 'Cimanggu'), ('Karangpucung', 'Karangpucung'), ('Cipari', 'Cipari'), ('Sidareja', 'Sidareja'), ('Kedungreja', 'Kedungreja'), ('Patimuan', 'Patimuan'), ('Gandrungmangu', 'Gandrungmangu'), ('Bantarsari', 'Bantarsari'), ('Kawunganten', 'Kawunganten'), ('Kampung Laut', 'Kampung Laut'), ('Jeruklegi', 'Jeruklegi'), ('Kesugihan', 'Kesugihan'), ('Adipala', 'Adipala'), ('Maos', 'Maos'), ('Kroya', 'Kroya'), ('Binangun', 'Binangun'), ('Sampang', 'Sampang'), ('Nusawungu', 'Nusawungu'), ('Cilacap Selatan', 'Cilacap Selatan'), ('Cilacap Tengah', 'Cilacap Tengah'), ('Cilacap Utara', 'Cilacap Utara')], default='Dayeuhluhur', max_length=35, verbose_name='Kecamatan')),
                ('jenis_kelamin', models.CharField(choices=[('LK', 'Laki-Laki'), ('PR', 'Perempuan')], max_length=15)),
                ('a', models.IntegerField(verbose_name='0-4 Tahun')),
                ('b', models.IntegerField(verbose_name='5-9 Tahun')),
                ('c', models.IntegerField(verbose_name='10-14 Tahun')),
                ('d', models.IntegerField(verbose_name='15-19 Tahun')),
                ('e', models.IntegerField(verbose_name='20-24 Tahun')),
                ('f', models.IntegerField(verbose_name='25-29 Tahun')),
                ('g', models.IntegerField(verbose_name='30-34 Tahun')),
                ('h', models.IntegerField(verbose_name='35-39 Tahun')),
                ('i', models.IntegerField(verbose_name='40-44 Tahun')),
                ('j', models.IntegerField(verbose_name='45-49 Tahun')),
                ('k', models.IntegerField(verbose_name='50-54 Tahun')),
                ('l', models.IntegerField(verbose_name='55-59 Tahun')),
                ('m', models.IntegerField(verbose_name='60-64 Tahun')),
                ('n', models.IntegerField(verbose_name='65-69 Tahun')),
                ('o', models.IntegerField(verbose_name='70-74 Tahun')),
                ('p', models.IntegerField(verbose_name='75+ Tahun')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PendudukLakiKecamatan',
        ),
        migrations.DeleteModel(
            name='PendudukPrKecamatan',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='dist_pdrb_migas',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='dist_pdrb_non_migas',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='inflasi_dod',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='inlfasi_yoy',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='laju_pert_pdrb_migas',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='laju_pert_pdrb_non_migas',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='pdrb_non_migas',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='pend_lk',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='pend_pr',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='sum_pert_pdrb_migas',
        ),
        migrations.RemoveField(
            model_name='kota',
            name='sum_pert_pdrb_non_migas',
        ),
        migrations.AddField(
            model_name='inflasi',
            name='total_inflasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='informasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='kesehatan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='pendidikan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='penyedia_pangan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='perawatan_pribadi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='perumahan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='rekreasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='sandang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='sembako',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='transportasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='hls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='ipm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='pertumbuhan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='ppp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='rls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='uhh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kemiskinan',
            name='gk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kemiskinan',
            name='p0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kemiskinan',
            name='p1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kemiskinan',
            name='p2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kemiskinan',
            name='ppdk_mskn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kemiskinan',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='angkatan_kerja',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='bekerja',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='bkn_angkatan_kerja',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='lainnya',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='pengangguran',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='sekolah',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenagakerja',
            name='urur_ruta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DistribusiPdrbMigas',
        ),
        migrations.DeleteModel(
            name='DistribusiPdrbNonMigas',
        ),
        migrations.DeleteModel(
            name='InflasiDod',
        ),
        migrations.DeleteModel(
            name='InflasiYoy',
        ),
        migrations.DeleteModel(
            name='LajuPertumbuhanPdrbMigas',
        ),
        migrations.DeleteModel(
            name='LajuPertumbuhanPdrbNonMigas',
        ),
        migrations.DeleteModel(
            name='PdrbNonMigas',
        ),
        migrations.DeleteModel(
            name='PendudukLaki',
        ),
        migrations.DeleteModel(
            name='PendudukPr',
        ),
        migrations.DeleteModel(
            name='SumberPertumbuhanPdrbMigas',
        ),
        migrations.DeleteModel(
            name='SumberPertumbuhanPdrbNonMigas',
        ),
        migrations.AddField(
            model_name='kota',
            name='pend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='penduduk_kota', to='bps.penduduk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kota',
            name='pend_kec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='penduduk_kecamatan', to='bps.pendudukkecamatan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kota',
            name='pdrb_migas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdrb_kota', to='bps.pdrb'),
        ),
        migrations.DeleteModel(
            name='PdrbMigas',
        ),
    ]
