# Generated by Django 3.2 on 2022-08-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0003_auto_20220830_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflasi',
            name='kategori',
            field=models.CharField(choices=[('Inflasi', 'Inflasi'), ('Inflasi DoD', 'Inflasi DoD'), ('Inflasi YoY', 'Inflasi YoY')], default=None, max_length=30),
            preserve_default=False,
        ),
    ]
