# Generated by Django 3.2 on 2022-08-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0003_auto_20220816_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflasi',
            old_name='transprotasi',
            new_name='transportasi',
        ),
    ]
