# Generated by Django 3.2 on 2022-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0004_rename_transprotasi_inflasi_transportasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflasi',
            options={'verbose_name': 'Inflasi'},
        ),
        migrations.AlterModelOptions(
            name='kota',
            options={'verbose_name': 'Kota'},
        ),
        migrations.AlterModelOptions(
            name='produkdomestikregionalbruto',
            options={'verbose_name': 'Produk Domestik Regional Bruto'},
        ),
        migrations.AlterField(
            model_name='produkdomestikregionalbruto',
            name='pengadaan_air_pengelolaan_sampah_dan_daur_ulang',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produkdomestikregionalbruto',
            name='perdagangan_besar_eceran_reparasi_mobil_motor',
            field=models.FloatField(default=0),
        ),
    ]
