# Generated by Django 3.2 on 2022-08-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0004_inflasi_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflasi',
            name='kategori',
            field=models.CharField(choices=[('Inflasi', 'Inflasi'), ('Inflasi DoD', 'Inflasi DoD'), ('Inflasi YoY', 'Inflasi YoY')], max_length=30, null=True),
        ),
    ]
