# Generated by Django 3.2 on 2022-08-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0005_alter_inflasi_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflasi',
            name='kategori',
            field=models.CharField(choices=[('Inflasi', 'Inflasi'), ('Inflasi DoD', 'Inflasi DoD'), ('Inflasi YoY', 'Inflasi YoY')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdrb',
            name='kategori',
            field=models.CharField(choices=[('PDRB Migas', 'PDRB Migas'), ('Distribusi PDRB Migas', 'Distribusi PDRB Migas'), ('Laju Pertumbuhan PDRB Migas', 'Laju Pertumbuhan PDRB Migas'), ('PDRB Migas', 'PDRB Non Migas'), ('Distribusi PDRB Non Migas', 'Distribusi PDRB Non Migas'), ('Laju Pertumbuhan PDRB Non Migas', 'Laju Pertumbuhan PDRB Non Migas')], max_length=250),
        ),
    ]
