# Generated by Django 3.2 on 2022-08-17 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0005_auto_20220816_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflasi',
            name='dibuat',
            field=models.DateField(auto_now_add=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='diubah',
            field=models.DateField(auto_now=True, verbose_name=django.utils.timezone.now),
        ),
    ]
