# Generated by Django 3.2 on 2022-08-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0006_auto_20220817_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflasi',
            old_name='dibuat',
            new_name='tanggal',
        ),
        migrations.RenameField(
            model_name='produkdomestikregionalbruto',
            old_name='dibuat',
            new_name='tanggal',
        ),
        migrations.RemoveField(
            model_name='inflasi',
            name='diubah',
        ),
        migrations.RemoveField(
            model_name='produkdomestikregionalbruto',
            name='diubah',
        ),
    ]
