# Generated by Django 3.2 on 2022-09-16 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0007_alter_inflasi_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama')),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bps.kategori'),
        ),
        migrations.AlterField(
            model_name='pdrb',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bps.kategori'),
        ),
    ]
