# Generated by Django 3.2 on 2022-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0007_auto_20220817_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflasi',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produkdomestikregionalbruto',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
