# Generated by Django 3.2 on 2022-09-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0008_auto_20220916_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategori'},
        ),
        migrations.AddField(
            model_name='tenagakerja',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflasi',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bps.kategori'),
        ),
        migrations.AlterField(
            model_name='pdrb',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bps.kategori'),
        ),
    ]
