# Generated by Django 3.2 on 2022-09-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0009_auto_20220919_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penduduk',
            options={'verbose_name': 'Penduduk', 'verbose_name_plural': 'Penduduk'},
        ),
        migrations.AlterModelOptions(
            name='pendudukkecamatan',
            options={'verbose_name': 'Penduduk Kecamatan', 'verbose_name_plural': 'Penduduk Kecamatan'},
        ),
    ]
