# Generated by Django 3.2 on 2022-08-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0009_auto_20220823_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kota',
            name='dist_pdrb_migas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribusi_pdrb_migas', to='bps.distribusipdrbmigas'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='dist_pdrb_non_migas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribusi_pdrb_non_migas', to='bps.distribusipdrbnonmigas'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='inflasi_dod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inflasi_dod_kota', to='bps.inflasidod'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='inlfasi_yoy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inflasi_yoy_kota', to='bps.inflasiyoy'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='laju_pert_pdrb_migas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laju_pertumbuhan_pdrb_migas', to='bps.lajupertumbuhanpdrbmigas'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='laju_pert_pdrb_non_migas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laju_pertumbuhan_pdrb_non_migas', to='bps.lajupertumbuhanpdrbnonmigas'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='sum_pert_pdrb_migas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sumber_pertumbuhan_pdrb_migas', to='bps.sumberpertumbuhanpdrbmigas'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='sum_pert_pdrb_non_migas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sumber_pertumbuhan_pdrb_non_migas', to='bps.sumberpertumbuhanpdrbnonmigas'),
        ),
    ]
