# Generated by Django 3.2 on 2022-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0010_auto_20220919_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='kota',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kota',
            name='nama_kota',
            field=models.CharField(max_length=50),
        ),
    ]
