# Generated by Django 3.2 on 2022-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0011_auto_20220919_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdrb',
            options={'verbose_name': 'Produk Domestik Regional Bruto', 'verbose_name_plural': 'Produk Domestik Regional Bruto'},
        ),
        migrations.AlterField(
            model_name='ipm',
            name='hls',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='ipm',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='pertumbuhan',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='ppp',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='rls',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='uhh',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
    ]
