# Generated by Django 3.2 on 2022-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0013_auto_20220922_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflasi',
            name='perlengkapan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
