# Generated by Django 3.2 on 2022-09-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0014_inflasi_perlengkapan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdrb',
            options={'verbose_name': 'Produk Domestik Regional Bruto', 'verbose_name_plural': 'Produk Domestik Regional Bruto'},
        ),
    ]
