# Generated by Django 3.2 on 2022-09-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0015_alter_pdrb_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendudukkecamatan',
            old_name='total',
            new_name='jumlah',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='a',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='b',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='c',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='d',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='e',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='f',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='g',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='h',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='i',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='j',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='k',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='l',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='m',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='n',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='o',
        ),
        migrations.RemoveField(
            model_name='pendudukkecamatan',
            name='p',
        ),
    ]
