# Generated by Django 3.2 on 2022-10-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0017_auto_20220925_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenagakerja',
            name='tkk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenagakerja',
            name='tpak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenagakerja',
            name='tpt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
